### PR TITLE
 2015 luminosity update for paper

### PR DESCRIPTION
**Pull request by capalmer85**

### CODE REVIEW

**Comment by capalmer85** [comment]
@gkrintir 

Full coverage for reprocessed golden json:
/afs/cern.ch/cms/CAF/CMSCOMM/COMM_DQM/certification/Collisions15/13TeV/Reprocessing/Cert_13TeV_16Dec2015ReReco_Collisions15_25ns_JSON.txt 

(NEW-OLD)/NEW=-0.22%

OLD
#Summary: 
+-------+------+-------+-------+-------------------+------------------+
| nfill | nrun | nls   | ncms  | totdelivered(/fb) | totrecorded(/fb) |
+-------+------+-------+-------+-------------------+------------------+
| 47    | 116  | 33212 | 33212 | 2.336026691       | 2.258065825      |
+-------+------+-------+-------+-------------------+------------------+
#Check JSON:
#(run,ls) in json but not in results: []

NEW
#Summary: 
+-------+------+-------+-------+-------------------+------------------+
| nfill | nrun | nls   | ncms  | totdelivered(/fb) | totrecorded(/fb) |
+-------+------+-------+-------+-------------------+------------------+
| 47    | 116  | 33213 | 33213 | 2.330868722       | 2.253012096      |
+-------+------+-------+-------+-------------------+------------------+
#Check JSON:
#(run,ls) in json but not in results: []

**Comment by gkrintir** [comment]
hi @capalmer85 

DT used in 4266, however, higher than the rest




I guess we might want to cross calibrate to PCC

**Comment by capalmer85** [comment]
This is beam halo.  Calibration looks ok, but the halo subtraction is not great.

**Comment by gkrintir** [comment]
shall we change to RAMSES instead?

**Comment by capalmer85** [comment]
Let's check BCM1F?  It should be really good for this fill.

**Comment by gkrintir** [comment]
Now that I am looking we anyway have PCC for a good portion so to avoid extra work PCC+RAMSES works for me, though still fine to have a look at BCM1F too.

**Comment by capalmer85** [comment]
(intL_Paper - intL_PAS)/intL_PAS = +0.7%


brilcalc command:
brilcalc lumi --normtag=normtag_PHYSICS.json  -i /afs/cern.ch/cms/CAF/CMSCOMM/COMM_DQM/certification/Collisions15/13TeV/Reprocessing/Cert_13TeV_16Dec2015ReReco_Collisions15_25ns_JSON.txt -u /fb

Updated lumi:
#Summary: 
+-------+------+-------+-------+-------------------+------------------+
| nfill | nrun | nls   | ncms  | totdelivered(/fb) | totrecorded(/fb) |
+-------+------+-------+-------+-------------------+------------------+
| 47    | 116  | 33213 | 33213 | 2.352418102       | 2.273841544      |
+-------+------+-------+-------+-------------------+------------------+
#Check JSON:
#(run,ls) in json but not in results: []

**Comment by plujan** [comment]
@capalmer85 @gkrintir This still has the same problems in normtag_dt.json that I notified you about last July:

```Error: malformed entry [u'dt15PaperV4', {u'251522': [[4, 3]]}]
Error: malformed entry [u'dt15PaperV4', {u'256674': [[2, 1]]}]
Error: malformed entry [u'dt15PaperV4', {u'256675': [[2, 1], [3, 163]]}]
Error: malformed entry [u'dt15PaperV4', {u'256728': [[2, 1], [4, 5]]}]
Error: malformed entry [u'dt15PaperV4', {u'257723': [[2, 1], [4, 8], [10, 108], [116, 131], [133, 148]]}]
Error: malformed entry [u'dt15PaperV4', {u'257725': [[2, 1], [4, 114], [116, 152], [154, 190], [192, 202], [204, 249]]}]
Error: malformed entry [u'dt15PaperV4', {u'257804': [[2, 1], [12, 12], [14, 14]]}]
Error: malformed entry [u'dt15PaperV4', {u'258425': [[2, 1], [5, 136]]}]
Error: malformed entry [u'dt15PaperV4', {u'259812': [[2, 1]]}]
Error: malformed entry [u'dt15PaperV4', {u'260540': [[2, 1]]}]
```

Please fix before merging.

**Comment by gkrintir** [comment]
thx @capalmer85 @plujan 

following the distributions [above](https://github.com/CMS-LUMI-POG/Normtags/pull/43#issuecomment-770035413) I scaled down DTs to match with PCC by 1.53 **only for 4266** (dt15PaperV5_test)

Screenshot from 2021-03-29 17-29-47

resulting comparison

newplot(1)

It doesn't change essentially nothing in 2015 lumi

 #Summary: 
+-------+------+-------+-------+-------------------+------------------+
| nfill | nrun | nls   | ncms  | totdelivered(/fb) | totrecorded(/fb) |
+-------+------+-------+-------+-------------------+------------------+
| 47    | 116  | 33213 | 33213 | 2.352418102       | 2.273841544      |
+-------+------+-------+-------+-------------------+------------------+

but I think it would be good to have it match with PCC in 4266. 

Also in 4266 RAMSES recorded is 0 so we can have these instances substituted by DTs.

Let me know if that sounds good to

- rename dt15PaperV5_test to dt15PaperV5
- update normtag_dt.json/normtag_PHYSICS.json from dt15PaperV4 to dt15PaperV5
- update normtag_PHYSICS.json from ramses15PaperV4 to dt15PaperV5 in 4266

btw @plujan shall we keep normtag_BRIL.json consistent?

**Comment by plujan** [comment]
Yes, do update normtag_BRIL.

**Comment by gkrintir** [comment]
addressed the items from [above](https://github.com/CMS-LUMI-POG/Normtags/pull/43#issuecomment-809733010)

i haven't 

- updated normtag_PHYSICS.json from ramses15PaperV4 to dt15PaperV5 in 4266 since the normtag correctly prioritized RAMSES given we don't have lumi for the other luminometers. Anyway there is no difference for the recorded between choosing ramses15PaperV4 to dt15PaperV5 in 4266, we have only more delivered lumi caused by LS at the end of Runs

#Summary in 4266 with substituting  ramses15PaperV4 with dt15PaperV5: 
+-------+------+------+------+-------------------+------------------+
| nfill | nrun | nls  | ncms | totdelivered(/ub) | totrecorded(/ub) |
+-------+------+------+------+-------------------+------------------+
| 1     | 7    | 1264 | 1264 | 62207.145686834   | 61118.909909317  |
+-------+------+------+------+-------------------+------------------+

#Summary in 4266 as is: 
+-------+------+------+------+-------------------+------------------+
| nfill | nrun | nls  | ncms | totdelivered(/ub) | totrecorded(/ub) |
+-------+------+------+------+-------------------+------------------+
| 1     | 11   | 1421 | 1294 | 72760.333051837   | 61187.770792680  |
+-------+------+------+------+-------------------+------------------+

**Comment by gkrintir** [comment]
+1 from me

after merging and syncing normtags in /cvmfs/cms-bril.cern.ch/cms-lumi-pog/Normtags I'll have a 2nd look for other mishaps

**Pull request merged**
