### PR TITLE
Remove bad PLT fills from 2016 normtag

### PR DESCRIPTION
**Pull request by plujan**
This update invalidates the fills marked bad in Rafael's spreadsheet. The full list is:
* 4947 -- This fill was affected by two long dropouts, since this was right before we implemented the auto recovery code. I've removed the parts during which the dropouts occurred (273725:1-1470 and 273730:2434-2533) so the rest of the fill should be OK. If it still looks bad we can invalidate the whole thing.
* 5038 -- Something strange was going on in this fill, as all of PLT/HFOC/BCM1F show much larger differences with each other than normal. Seems simplest to just invalidate this for PLT.
* 5288 -- This is the PLT HV test fill and so definitely bad for PLT.
* 5406, 5424, 5427, 5448, 5451 -- these are late-2016 fills which show significant deviations in the HFOC/PLT ratio over the course of the fill, probably because we can see the effect of recovery/radiation damage through the course of the fill. In principle these could be fixed with some more attention but for now it's probably simplest to just invalidate them.

@capalmer85 , please have a look. Also, if you can remind me of the latest sigmavis to use, I can update the 2016 normtag (either in this PR or afterwards, whichever's more convenient).

### CODE REVIEW

**Comment by capalmer85** [comment]
5038 is bad for HFOC.  I suggest comparing plt to pcc before you invalidate
it.

**Comment by plujan** [comment]
Yeah, there's still a significant discrepancy (bcm1f16v1/pltzero16RAMv1/pcc16PaperV2). Here's the plot:

**Comment by capalmer85** [comment]
Please use xsec = 329.2 µB with efficiency of 1.0 in fill 4954

**Comment by capalmer85** [comment]
btw, I did not remove bad parts of DT and RAMSES.  I just moved the _2016.json into the main one.  Since you are looking at the spreadsheet, could you also invalidate what was suggested there for DT and RAMSES?

**Comment by plujan** [comment]
I took a more detailed look at the DT and RAMSES fills in the spreadsheet, and I'm not sure all of them actually need to be invalidated. I'll send an email to you and Rafael with the full details.

**Comment by capalmer85** [comment]
Thanks! Great!

**Comment by plujan** [comment]
per email discussion, it looks like 5038 is actually best with DT/RAMSES/PLT (which agree with each other quite well now) so I've restored 5038 to the valid list for PLT.

**Comment by capalmer85** [comment]
Hi Paul,

Thanks!  Can you remove 5038 from PCC's normtag_x.json file?  That's
runs 275656-275659.

Cheers,
Chris

**Comment by plujan** [comment]
Sure, I'll put that in the other PR just to try to keep things clean.

**Pull request merged**
