### PR TITLE
 2016 luminosity update for paper

### PR DESCRIPTION
**Pull request by capalmer85**
Update normtags per luminometer and composite normtag in physics

### CODE REVIEW

**Comment by capalmer85** [comment]
@gkrintir 

OLD
#Summary: 
+-------+------+--------+--------+-------------------+------------------+
| nfill | nrun | nls    | ncms   | totdelivered(/fb) | totrecorded(/fb) |

+-------+------+--------+--------+-------------------+------------------+
| 144   | 392  | 231829 | 231811 | 37.420052680      | 35.882515396     |
+-------+------+--------+--------+-------------------+------------------+
#Check JSON:
#(run,ls) in json but not in results: []

NEW
+-------------+-------------------+------+------+----------------+---------------+
#Summary: 
+-------+------+--------+--------+-------------------+------------------+
| nfill | nrun | nls    | ncms   | totdelivered(/fb) | totrecorded(/fb) |
+-------+------+--------+--------+-------------------+------------------+
| 144   | 392  | 231829 | 231811 | 37.598607496      | 36.071268842     |
+-------+------+--------+--------+-------------------+------------------+
#Check JSON:
#(run,ls) in json but not in results: []

**Comment by gkrintir** [comment]
hi @capalmer85 I had a check on normtags fill 4954 needs to be fixed

brilcalc lumi --normtag normtag_PHYSICS.json -f 4954

| 274104:4954 | 05/27/16 13:08:05 | 29  | 29   | -29.762236380   | -4.915753903    |
| 274105:4954 | 05/27/16 13:25:27 | 17  | 17   | -17.446828223   | -6.427374249    |
| 274106:4954 | 05/27/16 13:41:52 | 14  | 14   | -14.367976183   | -5.300637337    |
| 274107:4954 | 05/27/16 13:51:28 | 5   | 5    | -5.131420065    | -3.922695359    |
| 274108:4954 | 05/27/16 13:58:21 | 10  | 10   | -10.262840131   | -8.658881615    |
+-------------+-------------------+-----+------+-----------------+-----------------+

Also RAMSES seems a bit high



since used in 4954 I think we might want to cross calibrate to PCC/HFOC

**Comment by capalmer85** [comment]
4954 should not have negative values now that I have invalidated DT in the fill.

**Comment by capalmer85** [comment]
(intL_paper - intL_PAS)/intL_paper = +1.1%

brilcalc command:
brilcalc lumi --normtag  normtag_PHYSICS.json -i  /afs/cern.ch/cms/CAF/CMSCOMM/COMM_DQM/certification/Collisions16/13TeV/Final/Cert_271036-284044_13TeV_PromptReco_Collisions16_JSON.txt -u /fb

output:
#Summary: 
+-------+------+--------+--------+-------------------+------------------+
| nfill | nrun | nls    | ncms   | totdelivered(/fb) | totrecorded(/fb) |
+-------+------+--------+--------+-------------------+------------------+
| 144   | 392  | 231829 | 231811 | 37.822207364      | 36.285760373     |
+-------+------+--------+--------+-------------------+------------------+
#Check JSON:
#(run,ls) in json but not in results: []

**Comment by gkrintir** [comment]
+1 from me

after merging and syncing normtags in /cvmfs/cms-bril.cern.ch/cms-lumi-pog/Normtags I'll have a 2nd look for other mishaps

**Pull request merged**
