### PR TITLE
Revalidation2016

### PR DESCRIPTION
**Pull request by plujan**
add new 2016 revalidation

### CODE REVIEW

**Comment by capalmer85** [comment]
Hi Paul,

I'm not sure why you made new files for normtag_pcc.json.  I would have
preferred that you merged this into those files so we could see the
differences wrt to what we already had.  Can you do that anyway?  I don't
think having _2016.json files makes sense.

Cheers,
Chris

**Comment by plujan** [comment]
Hi Chris,

Yes, the plan is indeed to merge the _2016 files into the main .json files, but I wanted to keep them separate for the moment so we can run the stability & linearity plots. Once we're happy with them then I'll go ahead and merge them into the existing files.

Note that the _2016 files already include lumisections that were invalidated in the existing .json files -- it's just to check for additional issues that weren't already accounted for (as well as to provide a ramses and dt normtag for 2016).

**Comment by capalmer85** [comment]
Hi Paul,

Ok great.  I was mainly interested in what the differences were for dt and
pcc.  I guess I'll do a diff at some point on my own.  Do you have a
feeling already if there were any big differences?

Cheers,
Chris

**Comment by plujan** [comment]
There's a total of 2215 LS that are in the new PCC normtag but not in the old normtag, and 4448 LS which are in the old normtag but not the new normtag, excluding some differences at the beginning of the year (the old normtag contains fills 4856-4874, which the new normtag does not include because PCC was not particularly stable for these very first fills; on the other hand, the new normtag starts at 4889 while the old normtag only restarts at 4905).

The full list is very long but most of the LSes that are in the old normtag but not the new normtag appears to be from the simple fact that the new normtag only includes STABLE BEAMS data while the old normtag also includes some times in ADJUST or earlier. The ones in the new normtag but not the old normtag seem to be mostly concentrated in ~10 fills, so we should probably have a closer look at those to figure out what's happening.

I've added a simple script in Scripts2016/checkMissingSegments.py which will tell you the full list of lumisections in one normtag and not the second, given two normtags.

**Pull request merged**
