### PR TITLE
put LUM16001 in normtag_PHYSICSS

### PR DESCRIPTION
**Pull request by gkrintir**
@plujan here it is

### CODE REVIEW

**Comment by gkrintir** [comment]
hi @plujan let me know whether that's fine to merge it

btw the file in 

/cvmfs/cms-bril.cern.ch/cms-lumi-pog/Normtags/

will be automatically updated or shall we intervene too? thx!

**Comment by plujan** [comment]
Hmm, it looks like a lot of the runs in the normtag are not actually covered by PCC. If I do something like
`brilcalc lumi --normtag normtag_PHYSICS.json -i /afs/cern.ch/cms/CAF/CMSCOMM/COMM_DQM/certification/Collisions15/5TeV/DCSONLY/json_DCSONLY.txt`
I get a lot of missing lumisections. I think it would probably make more sense to include only the lumisections for which PCC data is actually present. (If I use the regular physics JSON, there's fewer missing lumisections, but still some.)

**Comment by gkrintir** [comment]
thx @plujan indeed we [had](https://hypernews.cern.ch/HyperNews/CMS/get/luminosity/643.html) LS with no PCC data and 100% deadtime

sure, so i can remove those and make the output less daunting; i am updating the PR

thx!

**Comment by gkrintir** [comment]
@plujan ok done:

output lumi from

`brilcalc lumi --normtag pcc5TeV15v3 -i /afs/cern.ch/cms/CAF/CMSCOMM/COMM_DQM/certification/Collisions15/5TeV/Cert_262081-262328_5TeV_PromptReco_Collisions15_25ns_JSON.txt`

and

`brilcalc lumi --normtag normtag_PHYSICS.json -i /afs/cern.ch/cms/CAF/CMSCOMM/COMM_DQM/certification/Collisions15/5TeV/Cert_262081-262328_5TeV_PromptReco_Collisions15_25ns_JSON.txt`

identical.

The difference for the two cases is 

> #(run,ls) in json but not in results:

vs

> Warning: problems found in merging -i and --normtag selections:

**Comment by plujan** [comment]
Looks good, I'll go ahead and merge. It would be nice if we could provide a secondary luminometer for those times (even if it doesn't affect the recorded luminosity), but that is of course a lower-priority project.

**Comment by plujan** [comment]
Oh, I forgot to answer your other question -- yes, you will need to update the cvmfs repository yourself also (there are directions on https://twiki.cern.ch/twiki/bin/view/CMS/LumiConvenerTasks on how to do so). If you don't have the appropriate permissions then please contact Zhen to be added to the appropriate group.

**Comment by gkrintir** [comment]
OK thanks done for all 3 replica locations.

**Pull request merged**
